// produtos.js
const produtos = [
  {
    nome: "Desafio 30 Dias",
    descricao: "Seque em Casa, Transforme seu corpo sem sair de casa!",
    imagem: "Produtos/SECANDO-EM-CASA-EM-30-DIAS_d25ce3597f1a4ef2a80c4b8db1216721.jpg",
    link: "https://pay.kiwify.com.br/GFeetjM?afid=PfCqLMe6"
  },
  {
    nome: "Investidor em 1 Hora",
    descricao: "Aprenda a Investir Como um Profissional em Apenas 60 Minutos!",
    imagem: "Produtos/Finanças.jpg",
    link: "https://kiwify.app/velJGLO?afid=r3XbHwm4"
  },
  {
    nome: "Marketing Digital",
    descricao: "Domine estratégias reais para ganhar dinheiro online!",
    imagem: "Produtos/MarketingDigital.png",
    link: "https://pay.kiwify.com.br/t9ZDmE2?afid=FWOy8LEH"
  }
];
